_extends: nextjs-blog:.github/release-drafter.yml
name-template: 'remote_$RESOLVED_VERSION'
tag-template: 'remote_$RESOLVED_VERSION'
tag-prefix: remote
include-labels:
  - 'remote'
include-paths:
  - 'apps/remote/'
