name: 'depcruise'
on:
  pull_request:

jobs:
  report:
    permissions:
      pull-requests: write
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.head_ref }}
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: config git url
        env:
          READONLY_GITHUB_TOKEN: ${{ secrets.PRIVATE_PAT }}
        run: |
          git config --global url."https://${READONLY_GITHUB_TOKEN}:x-oauth-basic@github.com".insteadOf "https://github.com"
      - name: install packages
        run: yarn --check-files --frozen-lockfile --non-interactive
      - name: set report
        run: echo "DEP_MERMAID=$(echo npx depcruise --output-type mermaid --config .dependency-cruiser.js src)" >> $GITHUB_ENV
      - name: generate report
        run: echo ${{ env.DEP_MERMAID }}
