name: 'depcruise'
on:
  pull_request:

jobs:
  report:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.head_ref }}
      - uses: MH4GF/dependency-cruiser-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cruise-script: yarn run -s depcruise
