name: 'depcruise'
on:
  pull_request:

jobs:
  report:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: MH4GF/dependency-cruiser-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cruise-script: yarn run -s depcruise
