name: Release Drafter

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.calver.outputs.version }}
    steps:
      - name: Generate Calendar Version
        id: calver
        run: echo "version=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_OUTPUT
        env:
          TZ: "Asia/Tokyo"
  remote:
    name: '[Remote] Draft release'
    needs: create-version
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@3f0f87098bd6b5c5b9a36d49c41d998ea58f9348 # v6.0.0
        with:
          config-name: release-drafter-remote.yml
          name: remote_${{ needs.create-version.outputs.version }}_release
          tag: remote_${{ needs.create-version.outputs.version }}_release
  client-owner:
    name: '[Client Owner] Draft release'
    needs: create-version
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@3f0f87098bd6b5c5b9a36d49c41d998ea58f9348 # v6.0.0
        with:
          config-name: release-drafter-client-owner.yml
          name: client-owner_${{ needs.create-version.outputs.version }}_release
          tag: client-owner_${{ needs.create-version.outputs.version }}_release
  measurement:
    name: '[Measurement] Draft release'
    needs: create-version
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@3f0f87098bd6b5c5b9a36d49c41d998ea58f9348 # v6.0.0
        with:
          config-name: release-drafter-measurement.yml
          name: measurement_${{ needs.create-version.outputs.version }}_release
          tag: measurement_${{ needs.create-version.outputs.version }}_release
